### ISSUE TITLE
Twinkle Toes: CAS changed background and no Sims

### ISSUE THREAD

**Issue by mrsvivacia** [ts4cc/lighting-mods#1]
After I copied the files as instructed I started up my game and had the following issue:
My CAS background had changed and the Sim was not visible.
The world looked amazing in less blue and I could play the game.
I removed all mods and tray items, cleared caches and restarted but had the same issue with CAS.
Rolling the game back to before I added the twinkle toes files fixed the issue.

![TS4_x64 2020-01-19 14-46-14 original](https://user-images.githubusercontent.com/60078055/72689606-1a35af80-3ae1-11ea-9dec-9ba2ef13dd0b.png)

**Comment by chelhuff** [comment]
Hello and sorry for seeing this so late! This issue is typically caused by copy/pasting lighting mod folders instead of the individual files within those folders. There's a .world file for CAS and twinkle toes doesn't include it (because it's not altered by the mod) so when you copy/paste an entire folder, that file is lost, which causes CAS to be rendered with this starry sky. Since you've rolled back your mod, what I recommend doing from here is when you install lighting mods in the future, ensure that there's a .world file with CAS in the name in the same folder as the base game world files. All the best!
